server:
  max-http-header-size: ${spring.servlet.multipart.max-file-size}
  #开启gzip压缩，提高首页启动速度
  compression:
    enabled: true
  tomcat:
    max-http-form-post-size: ${spring.servlet.multipart.max-file-size}
common:
  file:
    max-upload-size: ${spring.servlet.multipart.max-file-size}
